### PR TITLE
feat: adding x/groups

### PR DESCRIPTION
**Pull request by damiannolan**
This PR is a work-in-progress.

- Adding `x/group` to application binary
- Adding guide for usage using `x/group`
- Adding `timeout` duration to `MsgSubmitTx`
- Cleanup of `intertx` module (removing unused code, adding godocs, minor improvements)

NOTE: This PR uses the tip of `release/v0.46.x` of cosmos-sdk. This includes a fix to `x/group` to correctly propagate events from exec msgs.

### CODE REVIEW

**Comment by fadeev** [comment]
Fails for me after:

```
icad tx group exec 2 --from $WALLET_1 --home ./data/test-1 --gas 500000 -b block
```

```
raw_log: '[{"msg_index":0,"events":[{"type":"cosmos.group.v1.EventExec","attributes":[{"key":"logs","value":"\"proposal
  execution failed on proposal 2, because of error message /intertx.MsgSubmitTx at
  position 0: failed to retrieve active channel for port icacontroller-cosmos1afk9zr2hn2jsac63h4hm60vl9z3e5u69gndzf7c99cqge3vzwjzsfwkgpd:
  no active channel for this owner\""},{"key":"proposal_id","value":"\"2\""},{"key":"result","value":"\"PROPOSAL_EXECUTOR_RESULT_FAILURE\""}]},{"type":"message","attributes":[{"key":"action","value":"/cosmos.group.v1.MsgExec"}]}]}]'
```

**Comment by damiannolan** [comment]
> Which is v0.46.0 + [your fix applied](https://github.com/fadeev/cosmos-sdk/blob/v0.46.2/x/group/keeper/msg_server.go#L750-L772).

Hey @fadeev, it looks like the code which you linked above contains a bug. On line 750 the current context is being overwritten using:

```go
ctx, flush := ctx.CacheContext()
```

If this line is removed I expect the events to be propagated correctly.
See: https://github.com/cosmos/cosmos-sdk/blob/main/x/group/keeper/msg_server.go#L749-L770

I would expect `SubmitTx` to fail if there is no open channel. You can also probably see after running the `MsgRegisterAccount` via proposal 1 that the first step in the handshake flow has taken place by inspecting ibc channels:

```
$BINARY q ibc channel channels
```

I expect this to return an interchain accounts channel with `STATE_INIT`. And as the events are not emitted the relayer does not react and complete the handshake via channel workers.

**Comment by fadeev** [comment]
Sorry, such a silly thing. Events are now emitted, thank you!

**Comment by fadeev** [comment]
When running the group example you provided, have you encountered this error? Hermes output:

```
2022-08-11T09:24:17.633951Z ERROR ThreadId(29) send_tx_check{id=bp9_uLhRJe}:send_tx{id=test-2}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call failed with status: status: Unknown, message: "codespace channel code 21: packet sequence is out of order: packet sequence ≠ next receive sequence (2 ≠ 1): receive packet verification failed: failed to execute message; message index: 1", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "271"} }
2022-08-11T09:24:17.634018Z ERROR ThreadId(85) packet_cmd{src_chain=test-1 src_port=icacontroller-cosmos1afk9zr2hn2jsac63h4hm60vl9z3e5u69gndzf7c99cqge3vzwjzsfwkgpd src_channel=channel-1 dst_chain=test-2}: will retry: schedule execution encountered error: failed with underlying error: gRPC call failed with status: status: Unknown, message: "codespace channel code 21: packet sequence is out of order: packet sequence ≠ next receive sequence (2 ≠ 1): receive packet verification failed: failed to execute message; message index: 1", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "271"} } retry_index=1
```

**Comment by damiannolan** [comment]
> Sorry, such a silly thing. Events are now emitted, thank you!

I just noticed in the code snippet you linked from your fork that `doExecuteMsgs` is called twice.
https://github.com/fadeev/cosmos-sdk/blob/v0.46.2/x/group/keeper/msg_server.go#L757-L759

Did you catch this when removing the overriding of the ctx? Maybe it has something to do with the hermes error you're experiencing now.

**Comment by fadeev** [comment]
Have you encountered an error like this with an ICA?

```
2022-08-12T11:24:18.664832Z ERROR ThreadId(132) packet_cmd{src_chain=earth src_port=icacontroller-cosmos1afk9zr2hn2jsac63h4hm60vl9z3e5u69gndzf7c99cqge3vzwjzsfwkgpd src_channel=channel-0 dst_chain=mars}: will retry: schedule execution encountered error: failed with underlying error: gRPC call failed with status: status: Unknown, message: "codespace sdk code 32: incorrect account sequence: account sequence mismatch, expected 7, got 6", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "113"} } retry_index=2
```

**Comment by damiannolan** [comment]
see: https://github.com/cosmos/ibc-go/blob/main/e2e/tests/interchain_accounts/groups_test.go

**Pull request closed without merging**
